src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz',
        2 => 'Bois'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    //Assert\Image(mimeTypes="image\jpeg") => bloque jpg
    /**
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $filename;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(min=5, max=255)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedroom;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postalCode;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    public function __construct() {
        $this->createdAt = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getImageFile(): ?File {
        return $this->imageFile;
    }

    public function setImageFile(File $imageFile): self {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
        return $this;
    }

    public function getFilename(): ?string {
        return $this->filename;
    }

    public function setFilename(string $filename): self {
        $this->filename = $filename;
        return $this;
    }

    public function getTitle(): ?string {
        return $this->title;
    }

    public function setTitle(string $title): self {
        $this->title = $title;
        return $this;
    }

    public function getSlug(): ?string {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string {
        return $this->description;
    }

    public function setDescription(?string $description): self {
        $this->description = $description;
        return $this;
    }

    public function getSurface(): ?int {
        return $this->surface;
    }

    public function setSurface(int $surface): self {
        $this->surface = $surface;
        return $this;
    }

    public function getRooms(): ?int {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self {
        $this->rooms = $rooms;
        return $this;
    }

    public function getBedroom(): ?int {
        return $this->bedroom;
    }

    public function setBedroom(int $bedroom): self {
        $this->bedroom = $bedroom;
        return $this;
    }

    public function getFloor(): ?int {
        return $this->floor;
    }

    public function setFloor(int $floor): self {
        $this->floor = $floor;
        return $this;
    }

    public function getPrice(): ?int {
        return $this->price;
    }

    public function getFormattedPrice(): ?string {
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self {
        $this->price = $price;
        return $this;
    }

    public function getHeat(): ?int {
        return $this->heat;
    }

    public function getHeatType(): ?string {
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self {
        $this->heat = $heat;
        return $this;
    }

    public function getCity(): ?string {
        return $this->city;
    }

    public function setCity(string $city): self {
        $this->city = $city;
        return $this;
    }

    public function getAddress(): ?string {
        return $this->address;
    }

    public function setAddress(string $address): self {
        $this->address = $address;
        return $this;
    }

    public function getPostalCode(): ?string {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): self {
        $this->postalCode = $postalCode;
        return $this;
    }

    public function getSold(): ?bool {
        return $this->sold;
    }

    public function setSold(bool $sold): self {
        $this->sold = $sold;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection {
        return $this->options;
    }

    public function addOption(Option $option): self {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }
        return $this;
    }

    public function removeOption(Option $option): self {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }
        return $this;
    }

}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use App\Entity\Option;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedroom')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                    'choices' => $this->getChoices()
                ])
            ->add('options', EntityType::class, [
                    'class' => Option::class,
                    'choice_label' => 'name',
                    'multiple' => true,
                    'required' => false
                ])
            ->add('imageFile', FileType::class, [
                'required' => false
                ])
            ->add('city')
            ->add('address')
            ->add('postalCode')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices() {
        return array_flip(Property::HEAT);
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Entity\Contact;
use App\Form\PropertySearchType;
use App\Form\ContactType;
use App\Repository\PropertyRepository;
use App\Notification\ContactNotification;
use Symfony\Component\Form;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Common\Persistence\ObjectManager;
use Twig\Environment;
use Knp\Component\Pager\PaginatorInterface;

class PropertyController extends AbstractController {

	/**
	* @var PropertyRepository
	*/
	private $repository;

	/**
	* @var ObjectManager
	*/
	private $em;

	public function __construct(PropertyRepository $repository, ObjectManager $em) {
        $this->repository = $repository;
        $this->em = $em;
    }

	/**
	* @Route("/biens", name="property.index")
	* @return Response
	*/
	public function index(PaginatorInterface $paginator, Request $request): Response {
		$search = new PropertySearch();
		$form = $this->createForm(PropertySearchType::class, $search);
		$form->handleRequest($request);
        $properties = $paginator->paginate(
        	$this->repository->findAllVisibleQuery($search), 
        	$request->query->getInt('page', 1),
        	12
    	);
        $this->em->flush();
		return $this->render('property/index.html.twig', [
			'courrent_menu' => 'properties_menu',
			'properties' => $properties,
			'form' => $form->createView(),
		]);
	}

	/**
	* @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-zA-Z\-]*"})
	* @return Response
	*/
	public function show(Property $property, String $slug, Request $request, ContactNotification $notification): Response {
		if($property->getSlug() !== $slug) {
			return $this->redirectToRoute('property.show', [
				'id' => $property->getId(),
				'slug' => $property->getSlug()
			], 301);
		}
		$contact = new Contact();
		$contact->setProperty($property);
		$form = $this->createForm(ContactType::class, $contact);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$notification->notify($contact);
			$this->addFlash('success', 'Votre message a été envoyé');
			return $this->redirectToRoute('property.show', [
				'id' => $property->getId(),
				'slug' => $property->getSlug()
			]);
		}
		return $this->render('property/show.html.twig', [
			'property' => $property,
			'form' => $form->createView()
		]);
	}

}
	

templates/property/_property.html.twig
<div class="card mb-4">
	{% if property.filename %}
		<img src="{{vich_uploader_asset(property, 'imageFile')}}" class="card-img-top" style="width: 100%; height: 5cm">
	{% else %}
		<img src="/images/default.png" class="card-img-top" style="width: 100%; height: 5cm">
	{% endif %}
	<div class="card-body">
		<h5 class="card-title">
			<a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">
				{{ property.title }}
			</a>
		</h5>
		<p class="card-text">{{ property.city }} - ({{ property.postalCode }})</p>
		<div class="text-primary" style="font-size: 2em; font-weight: bold">
			{{ property.formattedPrice }} €
		</div>
	</div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}A acheter{% endblock %}

{% block body %}

	<div class="jumbotron">

		<div class="container">

			{{ form_start(form, {'attr': {'novalidate': 'novalidate'} } ) }}
				<div class="form-row align-items-end">
					<div class="col-md-3">{{form_row(form.maxPrice)}}</div>
					<div class="col-md-3">{{form_row(form.minSurface)}}</div>
					<div class="col-md-3">{{form_row(form.options)}}</div>
					<div class="col-md-3">
						<div class="form-group">
							<button class="btn btn-primary">Rechercher</button>
						</div>
					</div>
				</div>
				{{ form_widget(form) }}
			{{ form_end(form) }}

		</div>

	</div>

	<div class="container mt-4">
		
		<h1 class="text-center">Les biens</h1>

		<div class="row">
			{% for property in properties if properties is not empty %}
				<div class="col-md-4">
					{% include('property/_property.html.twig') %}	
				</div>
			{% else %}
				<div class="alert alert-danger">Aucune propriété ne correspond à votre recherche ! <div>
			{% endfor %}
		</div>

		<div class="pagination">
			{{ knp_pagination_render(properties) }}
		</div>

	</div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ property.title }}{% endblock %}

{% block body %}

	<div class="jumbotron">

		<div class="container">

			{% for message in app.flashes('success') %}
				<div class="alert alert-success">
					{{message}}
				</div>
			{% endfor %}

			{% if not form.vars.valid %}
				<div class="alert alert-danger">
					Le formulaire est mal rempli
				</div>
			{% endif %}

			<div class="row">

				<div class="col-md-8">
						{% if property.filename %}
							<img src="{{vich_uploader_asset(property, 'imageFile')}}" class="" style="width: 600px; height: 300px">
						{% else %}
							<img src="/images/default.png" class="" style="width: 600px; height: 300px">
						{% endif %}
				</div>

				<div class="col-md-4">
					<div class="container">
						<h3> {{ property.title }} </h3>
						<h2> {{ property.rooms}} pièces - {{ property.surface }} m²</h2>
						<div class="text-primary" style="font-size:3rem"> {{ property.formattedPrice }} €</div>
						<a href="#" class="btn btn-primary">Contacter l'agence</a>
						<div id="contactForm" class="mt-4">
							{{ form_start(form, {'attr': {'novalidate': 'novalidate'} } ) }}
								<div class="row">
									<div class="col-md-6">{{form_row(form.firstname)}}</div>
									<div class="col-md-6">{{form_row(form.lastname)}}</div>
								</div>
								<div class="row">
									<div class="col-md-6">{{form_row(form.phone)}}</div>
									<div class="col-md-6">{{form_row(form.email)}}</div>
								</div>
								{{ form_rest(form) }}
								<div class="form-group">
									<button class="btn btn-primary">Envoyer</button>
								</div>
							{{ form_end(form) }}
						</div>
					</div>
				</div>

			</div>

		</div>

	</div>

	<div class="container">

		</nav>

		<p>{{property.description | nl2br}}</p>

		<div class="row">

			<div class="col-md-8">
				<h2> Caractéristiques </h2>
				<table class="table table-striped">
					<tr><td>Surface habitable</td><td>{{property.surface}} m²</td></tr>
					<tr><td>Nombre de pièces</td><td>{{property.rooms}}</td></tr>
					<tr><td>Nombre d'étages</td><td>{{property.floor}}</td></tr>
					<tr><td>Nombre de chambres</td><td>{{property.bedroom}}</td></tr>
					<tr><td>Chauffage</td><td>{{property.heatType}}</td></tr>
				</table>
			</div>

			<div class="col-md-4">
				<h2> Spécificités </h2>
				<ul class="list-group">
					{% for option in property.options if property.options is not empty %}
						<li class="list-group-item">{{ option.name }}</li>
					{% else %}
					<li class="list-group-item">Pas de spécificités</li>
					{% endfor %}
				</ul>
			</div>

		</div>

	</div>

{% endblock %}